### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by jimfb**
"should update" or "should be updated", but not "should updated".

### CODE REVIEW

**Comment by passy** [comment]
@jimfb It looks like you're still using your `@fb.com` email address. I think this is why the shipit bot is upset. :)

Thanks for all the fixes!

**Comment by jimfb** [comment]
@facebook-github-bot Ok, I changed/updated my primary email for this account.

I tried to re-sign the CLA, but I got this error:
screen shot 2017-04-22 at 9 22 45 pm


@passy Maybe poke the github bot and see if changing the email address was sufficient to fix things?

**Comment by passy** [comment]
@jimfb I think the bot works on a commit basis. This one here is still signed with `From: Jim <jsproch@fb.com>`.

**Comment by passy** [comment]
Ah, never mind. #123 has a gmail one. I'll check the bot again. :)

**Comment by fredemmott** [comment]
The bot is per-github-account.

**Comment by passy** [comment]
@jimfb Sorry that this is taking so long. Have you heard anything back from cla@?

**Comment by passy** [comment]
Fixed as well.

**Pull request closed without merging**
