### PR TITLE
added proguard rules

### PR DESCRIPTION
**Pull request by mishrabhilash**

### CODE REVIEW

**Comment by passy** [comment]
What warnings do you otherwise see? Is there something we should address directly instead?

**Comment by mishrabhilash** [comment]
These are the warnings that I get.

```
Warning: com.facebook.fbui.textlayoutbuilder.proxy.StaticLayoutProxy: can't find referenced method 'StaticLayout(java.lang.CharSequence,int,int,android.text.TextPaint,int,android.text.Layout$Alignment,android.text.TextDirectionHeuristic,float,float,boolean,android.text.TextUtils$TruncateAt,int,int)' in library class android.text.StaticLayout
Warning: com.facebook.litho.TransitionManager$AnimationState: can't find referenced class com.facebook.litho.TransitionManager$ChangeType
Warning: com.facebook.litho.TransitionManager$TransitionsAnimationBindingListener: can't find referenced class com.facebook.litho.TransitionManager$ChangeType
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJB: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListJBMR2: can't find referenced class android.view.DisplayList
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.HardwareCanvas
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListLollipop: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.DisplayListCanvas
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.DisplayListCanvas
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListMarshmallow: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListNougat: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListNougat: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListNougat: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListNougat: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListNougat: can't find referenced class android.view.RenderNode
Warning: com.facebook.litho.displaylist.DisplayListNougat: can't find referenced class android.view.RenderNode
```

**Comment by passy** [comment]
@mishrabhilash Thanks for clarifying. That makes sense. But I have two concerns: The README isn't a great place for this. It would be better to add this to the FAQ, in my opinion. Secondly, I think we shouldn't ignore all warnings but limit it to the ones we see above. The list is unlikely to expand a lot in the future. `com.facebook.fbui.textlayoutbuilder` is also a different project, but I guess we can include it here.

Would you be okay making those changes?

**Comment by mishrabhilash** [comment]
For first, a lot of libraries from community mention the proguard info in
README. Eg glide <https://github.com/bumptech/glide>, picasso
<https://github.com/square/picasso>, retrofit
<https://github.com/square/retrofit>. I looked for them in README first as
well.  So, I assume that is the place people usually look for.

Second, I will make those changes straightaway and limit the rules to the
warnings mentioned and modify PR. (or should I if we are not going to put
them in README)

**Comment by passy** [comment]
@mishrabhilash The point about other projects is well made, but we try to keep our README very lean. The current things we mention there are the absolute basics about what the project is, not how to use it. We keep the latter in our docs which are way easier to organize.

Thanks for doing this. :)

**Comment by vinc3m1** [comment]
Can we just add it to https://github.com/facebook/litho/blob/master/litho-annotations/src/main/java/com/facebook/proguard/annotations/proguard_annotations.pro

which get pulled in by android projects through the .aar automatically?

**Comment by mishrabhilash** [comment]
closing this pull request as moved it to FAQs

**Pull request closed without merging**
