### PR TITLE
Add a onComponentTreeReleased method to RenderInfo.

### PR DESCRIPTION
**Pull request by tnorman42**
This allows for cleanup when RecyclerBinder disposes of the ComponentTree.

### CODE REVIEW

**Comment by muraziz** [comment]
We are working towards some sort of ondestroy callback which could be overlapping with this PR. Let me pull in and ask for feedback from folks.

**Comment by astreet** [comment]
Is this only as a workaround for the lack of onDestroy in the meantime?

**Comment by tnorman42** [comment]
> Is this only as a workaround for the lack of onDestroy in the meantime?

Yes, if we had an onDestroy lifecycle method, we wouldn't need this. So if you'd rather wait until that kind of lifecycle method might be available, we can just keep this as a local change until then.

**Comment by muraziz** [comment]
@tnorman42 yeap, let's do that, we'll be providing onDestroy callback pretty soon.

**Pull request closed without merging**
