### PR TITLE
Fixes RTL custom ellipsis text and when less wide than the default

### PR DESCRIPTION
**Pull request by tnorman42**
We were observing this when the custom ellipsis text was set to ' ', for example.

### CODE REVIEW

**Comment by tnorman42** [comment]
We've had trouble writing Litho tests that work with fonts and sizing; we were unable to create any tests using ComponentTestHelper that would properly size or truncate a TextSpec. For this issue, we verified it with a screenshot test. Would you be satisfied with a before/after screenshot? Past that, given that I don't see any existing truncation tests, I don't think it's feasible for us to add them.

**Comment by muraziz** [comment]
Ah interesting, we also have our own screenshot tests infra, so we can probably integrate your tests into ours if you could provide component description with all props and sizes. Yeah, screenshot would be useful to compare after we created equivalent tests in our infra.

**Comment by tnorman42** [comment]
I'm having trouble reproducing this now. I think it may have been isolated to a certain OS version.

**Comment by astreet** [comment]
Is this still relevant?

**Comment by vinc3m1** [comment]
Pretty sure it's still relevant

**Comment by colriot** [comment]
@tnorman42 @vinc3m1 if it's still relevant, can you, please, provide screenshots and component descriptions as @muraziz mentioned before?

**Comment by tnorman42** [comment]
I've synced and updated this to include a related fix for RTL text. Will provide screenshots separately.

**Comment by tnorman42** [comment]
LTR text test cases before the fix:
litho-text-ltr-before

LTR text test cases after the fix:
litho-text-ltr-after

**Comment by tnorman42** [comment]
RTL test cases before the fix:
litho-text-rtl-before

RTL test cases after the fix:
litho-text-rtl-after

**Comment by tnorman42** [comment]
Test case data:

Basically these test cases are loaded from the data below with:

Text text =
Text.create(context)
.text(text.content)
.maxLines(max_lines)
.customEllipsisText(truncation_text.content)
.build();
// and then all test cases added to a Column

#1
      text {
        content: "Single line truncation\nLine2\nLine3\nLine4"
      }
      max_lines: 1

#2
      text {
        content: "Single line truncation with short truncation text\nLine2\nLine3\nLine4"
      }
      max_lines: 1
      truncation_text { content: "." }

#3
      text {
        content: "Single line truncation with long truncation text\nLine2\nLine3\nLine4"
      }
      max_lines: 1
      truncation_text { content: "ABCDEFGHIJKL" }

#4
      text {
        content: "Single line truncation, for very very very very very very very very very very long sentence"
      }
      max_lines: 1

#5
      text {
        content: "Single line truncation, for very very very very very very very very very very long sentence"
      }
      max_lines: 1
      truncation_text { content: "." }

#6
      text {
        content: "Single line truncation, for very very very very very very very very very very long sentence"
      }
      max_lines: 1
      truncation_text { content: "ABCDEFGHIJKL" }

#7
      text {
        content: "Multi line truncation.\nLine2\nLine3\nLine4"
      }
      max_lines: 2

#8
      text {
        content: "Multi line truncation with short truncation text.\nLine2\nLine3\nLine4"
      }
      max_lines: 2
      truncation_text { content: "." }

#9
      text {
        content: "Multi line truncation with long truncation text.\nLine2\nLine3\nLine4"
      }
      max_lines: 2
      truncation_text { content: "ABCDEFGHIJKL" }

#10
      text {
        content: "Multi line truncation with long second line and long truncation text.\nThis is a very very very very very very very very very very long Line2\nLine3\nLine4"
      }
      max_lines: 2

#11
      text {
        content: "Multi line truncation with long second line and long truncation text.\nThis is a very very very very very very very very very very long Line2\nLine3\nLine4"
      }
      max_lines: 2
      truncation_text { content: "ABCDEFGHIJKL" }

#12
      text {
        content: "Multi line truncation with long second line and short truncation text.\nThis is a very very very very very very very very very very long Line2\nLine3\nLine4"
      }
      max_lines: 2
      truncation_text { content: "." }

**Comment by xiphirx** [comment]
Thanks for the screenshots @tnorman42, I'm assuming that the location of the ellipsis is opposite in the RTL screenshots because you're using a LTR language/locale?

How does it look for, say, Arabic or Hebrew?

Otherwise, these changes look fine to me. Thanks for looking into it and fixing!

**Pull request closed without merging**
