### PR TITLE
Add appendItem for RecyclerBinder

### PR DESCRIPTION
**Pull request by leochuan**
Pull request for #203

### CODE REVIEW

**Comment by passy** [comment]
Thanks for your contribution!

Could you add some tests for this too? :) The proper suite for this would be 
https://github.com/facebook/litho/blob/master/litho-it/src/test/java/com/facebook/litho/widget/RecyclerBinderTest.java

**Comment by leochuan** [comment]
@passy ok :)

**Comment by leochuan** [comment]
@passy It's done, cause `appendItem` internally call the method `insertItemAt` so I think test whether it insert items at tail is enough.

**Comment by passy** [comment]
Thanks a lot! Yeah, that sounds sensible. I was thinking about potential issues with the runtime complexity here, but `getItemCount()` should be O(1) as long as we use an `ArrayList` to hold on to the items.

**Pull request closed without merging**
