### PR TITLE
Allow EventData to return current instance

### PR DESCRIPTION
**Pull request by pavlospt**
* Using `apply` function from Kotlin, we can have a Builder pattern-like behavior, allowing call chaining.

### CODE REVIEW

**Comment by pavlospt** [comment]
You mean `..) : EventData = apply { ... ` ?

**Comment by passy** [comment]
Sorry for being so slow. Yes. :)

**Comment by pavlospt** [comment]
@passy Great, will add it! Also just out of curiosity, why would you want this?

**Comment by passy** [comment]
@pavlospt I like type signatures. :) I think it's good practice to keep them around unless you're returning `Unit`.

**Pull request closed without merging**
