### PR TITLE
formatting and typo

### PR DESCRIPTION
**Pull request by Pavneet-Sing**

### CODE REVIEW

**Comment by dsyang** [comment]
Thanks for the contribution!

**Comment by dsyang** [comment]
Hey @Pavneet-Sing , can you squash your commits into just one?

**Comment by Pavneet-Sing** [comment]
@dsyang ok let me try

**Comment by Pavneet-Sing** [comment]
there is only one branch now , i guess i have to initiate a new pull request by closing this one?

**Comment by dsyang** [comment]
I think you can squash it locally then force-push it to this branch in your fork.  That should update this PR to have just one commit

**Comment by Pavneet-Sing** [comment]
yeah that's the issue , i am not on command-line and seems like i can't do force push on github site , let me see, send you new PR when i am done , thanks for your time , you've been really supporting

**Pull request closed without merging**
