### PR TITLE
Transfer external Annotations on Component fields

### LINKED ISSUE #343: Transfer @Nullable annotation from @Prop to generated Component
When marking a `@Prop` as `@Nullable`, the generated component should have the field and the parameter in the builder method also generated with `@Nullable`. This helps static analysis.

Point of contact: @passy

### PR DESCRIPTION
**Pull request by pavlospt**
* Builder methods were already including external Annotations
for each Prop. Followed a same approach to transfer them on the Component
fields as well.

Closes #343

### CODE REVIEW

**Comment by passy** [comment]
Sweet! Could you perhaps modify one of our integration tests to include a `@Nullable` field to see how the change affects the generated code?

**Comment by passy** [comment]
This one might be a good candidate: https://github.com/facebook/litho/blob/master/litho-it/src/test/resources/processor/TestLayoutSpec.java

**Comment by pavlospt** [comment]
Sure will update the PR with a test case for it!

**Comment by pavlospt** [comment]
@passy added 2 tests cases: 

- `ProcessorIntegrationTest.java`
- `ComponentBodyGeneratorTest.java`

**Comment by passy** [comment]
A dream! Thank you. I'll try and get that through internal review quickly. :)

**Comment by pavlospt** [comment]
@passy let me check the CI failure!

**Comment by passy** [comment]
@pavlospt Looks like there's a missing buck dep on the jsr annotations.

**Comment by pavlospt** [comment]
@passy yeap found that as well! Still figuring out `BUCK` but it was easier than last time 😂

**Pull request closed without merging**
