### PR TITLE
Migrate documentation to Docusaurus v2

### PR DESCRIPTION
**Pull request by teikjun**
## Summary

Hi there! As discussed in #669, we would like to migrate Litho's documentation website to Docusaurus 2. 

Docusaurus 2 brings about many improvements:
- Client-side rendering with prerendering (site renders without JavaScript!)
- Embeddable interactive React components within markdown via MDX
- Docusaurus sites are React apps built with modern Javascript ecosystem tooling

In this PR, we've migrated the documentation over to Docusaurus 2 (in `/website` directory) while leaving the `/docs` directory intact. 
We've matched the design of the original site as much as possible, so that the transition will be smooth for users of Litho.

## Changelog

Migrate documentation website from Jekyll to Docusaurus v2

## Test Plan

The test site is up! https://litho-deploy.vercel.app

@Drewbi and I are looking to improve the documentation site further based on your feedback. 
Please let us know what you think! :)

cc @yangshun

### CODE REVIEW

**Comment by Drewbi** [comment]
# Summary
Reviewing 1,231 files might be a little tiresome (Fear not, most of them are javadoc copies) so I'll try and give a rundown on where to look for important changes and why we made some of the decisions we did.

## Docs

The first thing we did after running the docusaurus init script was to move across all the doc files and other assets. 
Changes made to docs were:
### Table links [#](https://github.com/MLH-Fellowship/litho/commit/5eecb85078f62b9a4cd1825fb5afc0c99f5ae510#diff-b7d035cabf0ee4c6ae91dae30d7991aa)
Some links included parentheses and were breaking the markdown syntax. Changed them into `<a>` tags.
### Doc links [#](https://github.com/MLH-Fellowship/litho/commit/4b86d3476bab5dc0fbc09dfefe1a990b241374f5#diff-6f5285e0b9c6b597d4d4f3f51f98b60f)
Fixed incorrect document links. [Also of note](https://github.com/MLH-Fellowship/litho/commit/6e169b181bd0036086d4586520813c38f9c01887).
[This page](https://github.com/MLH-Fellowship/litho/blob/docusaurus-v2-migration/website/docs/common-props.md) is missing many entries so might be useful to add a work in progress banner.
### Images [#](https://github.com/MLH-Fellowship/litho/commit/102132d8321b8aae2bc8ab2be7b1598c7142f980#diff-6f5285e0b9c6b597d4d4f3f51f98b60fR15)
Fixed images to point to the correct route and for sized images to use html tags
### Callouts [#](https://github.com/MLH-Fellowship/litho/commit/ce3ceddbb6b6a477c0d0f7eef6066189d4929cf6#diff-8d795eda3562fb07abb14ce48da5c5d8R250-R252)
Changed callouts to use Docusaurus' [admonitions](https://v2.docusaurus.io/docs/next/markdown-features#calloutsadmonitions).

Previous:

Updated:


Another Example
Previous:

Updated:


### Escape angle brackets [#](https://github.com/MLH-Fellowship/litho/commit/ee74e0dd416ba7300b870bfd1848c1022f8a105d#diff-78f447de5a8c9b21a46183aa4bab35c8R21)
mdx was getting confused at angle brackets such as `DynamicValue<T>` so we escaped them using backticks.

### Fixed video elements [#](https://github.com/MLH-Fellowship/litho/commit/ee74e0dd416ba7300b870bfd1848c1022f8a105d#diff-78f447de5a8c9b21a46183aa4bab35c8R27-R30)
Used function `useBaseUrl` to get url of videos correctly and fixed some of the attributes.

### Added language support [#](https://github.com/MLH-Fellowship/litho/commit/051712b38fd61a7fb69bef8da9029c582a0e1522)
Added groovy and kotlin syntax highlighting for code blocks.

### Fixed image wrapping [#](https://github.com/MLH-Fellowship/litho/commit/4c55d3891ffc5aa1b1deb7e57d8b1daba5f6787d#diff-6f5285e0b9c6b597d4d4f3f51f98b60fR31)
When floating images on the right some elements may overlap. To fix this altered some of the html line breaks (`<br />`).

### Convert tabbed content [#](https://github.com/MLH-Fellowship/litho/commit/dc1c7acb1687556ec8fb859563c2da5e51a66850#diff-d1fcc9daf8a14cc81b9aa159df2d176d) 
Previously tabbed content such as multi language selection was contained in separate files. We used a component from docusaurus with the same functionality but had to move all the content into one file.


### Hid table of content for tabbed pages [#](https://github.com/MLH-Fellowship/litho/commit/551db449754e87c25c5c2bd7da4fb5ab0567e197#diff-d1fcc9daf8a14cc81b9aa159df2d176d)
If you leave them unhidden it shows all the categories not just the visible one.

### Updated widget buttons [#](https://github.com/MLH-Fellowship/litho/commit/f81bddeeba8ebb17a5964c72b1a36e5b460fe4bb#diff-e4bde252142f37faa63f8cf98b7b7b90)
Made custom component for buttons and used theme css to style them. The list of seemingly random attributes above the buttons might be something to check out as it may be mistakenly left in.


## Config

### Title
Unfortunately recreating the home page title of 'Litho | {description}' is hard to do in docusaurus as the consistent format is '{ pageTitle} | Litho' so in if you tried to add it as a custom title it would look like 'Litho | A declaritive ... | Litho' which is undesirable. We opted to just leave the description out.

### Dark mode/Light mode
Docusaurus support dark/light toggle but in an effort to support a colored title bar we had to add custom colors to the nav links and the mobile nav toggle meaning extra work would be needed to support both so we opted to disable the feature.

### Footer
The footer of docusaurus requires several lists of links instead of the simple footer on the old website. The same style could be easily achieved by [swizzling](https://v2.docusaurus.io/docs/using-themes/#swizzling-theme-components) the footer allowing you to customize it like any react component. Docusaurus strongly recommend against this however at least until they leave beta as they may change the props being passed into the footer in the future, thereby breaking the component.
I also think that having 4 categories of links looks better than 3 so if you have any extra links you can think of that would be useful to have in the footer I'd encourage you to add them.

### Code highlighting (Prism)
Docusaurus uses [Prism](https://prismjs.com/#supported-languages) for syntax highlighting and extra languages can be added as well as color themes. I found that the color theme for github fit the brand colors of Litho surprisingly well.


### Sass support
Considering most of the previous css was written in sass we figured it would be useful for us and future stylers to be able to reuse code/continue using sass.

### Sidebar config
Docusaurus allows for side bar ordering to be written in Javascript object notation and allows for multiple different sidebars if you need it. Another possibility we didn't end up implementing was the [always expanded](https://v2.docusaurus.io/docs/docs-introduction/#collapsible-categories) option for side bars.

## Home page
Pages in docusaurus are just react components that use the Layout component for styling. We were able to match the styling of the home page quite well with a few exceptions. 

### Navbar
We weren't able to hide the navbar logo or the search bar while on the home page. Accessing these elements is quite difficult without swizzling the component or making your own theme. I also wasn't able to find a way of keeping the navbar at the top of the page only on the home page as docusaurus default layout is a little all or nothing in terms of customization.

### Font
We have matched the font on the home page but left the rest of the site as docusaurus' default font `Menlo` which looks quite nice.

### CSS
Docusaurus uses [Infima](https://facebookincubator.github.io/infima/) for most of it's stylings and there are many classes that can be utilized. We probably did not utilize them very well. In fact although the css all works well it is not very clean and reuses many values that could be provided as root css variables or sass variables.  

## What's Left

There are a few improvements that can be made but some of them were a little outside our expertise or just not entire necessary for a well functioning website.

### CI/CD configuration
We left the old docs folder in the PR so that we wouldn't break anything while we merge. Setting this up is very necessary and should be done as soon as you want to transition over to the new site.  

### Angolia
From what I understand about angolia docsearch the new links should be updated as soon as the new site is traversed but some of the search links are currently broken. Another consideration is that all of the top level search links have a #main_wrap navigation tag which was used on the old site to start any page at the top. Currently this doesn't link to anything so you'll find yourself at the bottom of some pages after using search links.

### Javadoc weirdness
Because the javadocs are hosted statically we weren't able to link to them without opening a new tab. This may be as simple as using a custom html link instead of the current href field.

### CSS cleanliness  
I think this is a remaining task as expansion of features such as dark/light mode would require some careful investigation of docusaurus'/infima's classes and root values as well as utilizing sass features better than they currently are. If there are any glaring problems I am more than willing to fix them before continuing with the migration.

## Conclusion
Sorry to make this comment so long but I feel it gives some insight into our decision making and can quickly highlight areas that may need attention. Thanks for reading 😅

**Comment by colriot** [comment]
Wow! @teikjun @Drewbi thanks a lot for working on that! 
It will take some time to review this, but thanks to your thorough description it would be less pain :)

**Comment by slorber** [comment]
Great PR and detailed changelog, the new site looks good to me.

That could be nice to have a dark mode 🤪

**Comment by muraziz** [comment]
Looks so nice: colors, spacing, new widgets, navigation. Thanks @teikjun for working on this!

**Comment by teikjun** [comment]
We've enabled dark mode on the same [test-site](https://litho-deploy.vercel.app/docs)! 
image

The SVGs show up with poor contrast in dark mode, but setting `background-color` of the SVG to white will resolve the issue :)

**Comment by Drewbi** [comment]
> The SVGs show up with poor contrast in dark mode, but setting `background-color` of the SVG to white will resolve the issue :)

I'm planning to go in today and clean up some of the CSS variables to help with dark mode

**Comment by colriot** [comment]
I've noticed that Litho version is not pulled in correctly, like:
```
implementation 'com.facebook.litho:litho-core:{{site.litho-version}}'
implementation 'com.facebook.litho:litho-widget:{{site.litho-version}}'
```
`{site.litho-version}` was a part of the website config before, to be able to update it in one place during the release

**Comment by teikjun** [comment]
> I've noticed that Litho version is not pulled in correctly, like:
> 
> ```
> implementation 'com.facebook.litho:litho-core:{{site.litho-version}}'
> implementation 'com.facebook.litho:litho-widget:{{site.litho-version}}'
> ```
> 
> `{site.litho-version}` was a part of the website config before, to be able to update it in one place during the release

We've just fixed this issue!
As before, the versions can be updated in one place `versionConfig.js` (found in the root directory).
The updated version will be reflected across all docs! :)

**Comment by JoelMarcey** [comment]
How are we on this? Are we good to go with the migration?

**Comment by Drewbi** [comment]
Should be all complete unless there’s any changes you can think of.

**Comment by muraziz** [comment]
I fixed internal errors, we should be ready for migration.

**Comment by muraziz** [comment]
Commit is merged, now we should be able to redirect website to new one. Will update here when it happens.

**Comment by colriot** [comment]
@Drewbi  @teikjun just for your info: we didn't just shelve your effort, we are currently working on integrating this into our internal docs publishing mechanism (this won't be Github Pages eventually, so we don't waste time on making Docusaurus work with them)

**Pull request closed without merging**
