### PR TITLE
Formatting and typo

### PR DESCRIPTION
**Pull request by Pavneet-Sing**

### CODE REVIEW

**Comment by dsyang** [comment]
Still looks like there's 4 commits :( @passy  does that matter when importing?

**Comment by Pavneet-Sing** [comment]
@dsyang yeah it is 4 oops, i thought you were saying that because of that failed check that was occurring due to one commit from a patch

**Comment by passy** [comment]
@dsyang Doesn't matter when importing.

Thanks, but this actually doesn't match up with our internal style guide. We follow the [Google Java Styleguide](https://google.github.io/styleguide/javaguide.html) and while we're not 100% conformant right now, we want to try to get at least all code we touch to follow it from now on. :)

**Comment by Pavneet-Sing** [comment]
You mean i violated this "Tab characters are not used for indentation" , sometimes it's kinda hard when you have to choose between space and tab

**Comment by passy** [comment]
@Pavneet-Sing In particular the alignment of assignments or similar things. This may look nicer at a glance but creates issues in code reviews as the addition of a single item can cause everything else to reflow, adding irrelevant line changes to the review. That's why most guidelines for larger codebases don't use it.

**Comment by Pavneet-Sing** [comment]
@passy Thank you for taking the time to enlighten me

**Comment by passy** [comment]
@Pavneet-Sing No problem. Thanks for the pull request. Keep them coming! :)

**Pull request closed without merging**
