### PR TITLE
Migrate usages of deprecated RuntimeEnvironment.application

### PR DESCRIPTION
**Pull request by chggr**
## Summary

RuntimeEnvironment.application has been deprecated in Robolectric 4
in favour of androidx ApplicationProvider.getApplicationContext().
This change migrates all usages of RuntimeEnvironment.application
in Litho to ApplicationProvider.getApplicationContext().

## Changelog

Migrates Litho testing infrastructure away from deprecated RuntimeEnvironment.application

## Test Plan

This change does not affect production code. Affected tests run successfully.

### CODE REVIEW

**Comment by chggr** [comment]
Hi @nicous, I hope you are well!

Just wanted to check your thoughts on this PR, thanks!

**Comment by nicous** [comment]
Hey @chggr this looks good. I've already imported it, will be merged probably next week.

**Comment by chggr** [comment]
Hi @nicous thanks very much! There were some merge conflicts that I have now resolved.

**Comment by chggr** [comment]
Hi @nicous, I hope you are well!

Just wanted to check whether you have any further feedback on this PR.
It is just cleaning up some tech debt in tests, is this something that could be merged?

Many thanks!

**Comment by nicous** [comment]
Hi @chggr sorry for the delay on this. I tried to merge this and there were a couple of other issues. I'll try to merge this today.

**Pull request closed without merging**
