### PR TITLE
Fix ellipsizing with styled custom ellipsis text

### PR DESCRIPTION
**Pull request by chggr**
## Summary

At the moment it seems that Litho is not measuring styled ellipsis text properly.
This PR creates a new text Layout for the custom ellipsis text and uses that to
calculate the text width and drive text truncation. It also caters for cases when
the text might be left aligned or have an RTL direction.

## Changelog

Fixes the way styled ellipsis text is measured.

## Test Plan

Unit tests have been added.

### CODE REVIEW

**Comment by chggr** [comment]
Hi team, this PR substitutes PR https://github.com/facebook/litho/pull/586. It is basically the same change, but I am taking it over and cleaning up the commits, since Tim has moved to another team. Please see below screenshots with manual tests in addition to the unit tests included in the commits:

Before:
before

After:
after

**Comment by vinc3m1** [comment]
bump?

**Comment by chggr** [comment]
Hi team, just to check whether you had a chance to look into this PR?

**Comment by colriot** [comment]
Thank you @chggr for fixing this!

**Pull request closed without merging**
